"""empty message

Revision ID: 1e8474619894
Revises: c4e9dd5e9af6
Create Date: 2025-12-01 18:03:24.474921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8474619894'
down_revision: Union[str, Sequence[str], None] = 'c4e9dd5e9af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hyperv_hosts_audit', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Время создания лога'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hyperv_hosts_audit', 'created_at')
    # ### end Alembic commands ###
