"""empty message

Revision ID: 22acae0a39c5
Revises: 81aaba046352
Create Date: 2025-12-26 12:05:53.372208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22acae0a39c5"
down_revision: Union[str, Sequence[str], None] = "81aaba046352"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clusters", sa.Column("db_name", sa.String(length=63), nullable=True))

    op.execute(
        """
        UPDATE clusters
        SET db_name = 'base_db_name'
        WHERE db_name IS NULL
        """
    )

    op.alter_column("clusters", "db_name", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clusters", "db_name")
    # ### end Alembic commands ###
