"""empty message

Revision ID: 81aaba046352
Revises: 1e8474619894
Create Date: 2025-12-15 14:05:00.820381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81aaba046352"
down_revision: Union[str, Sequence[str], None] = "1e8474619894"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hyperv_hosts", sa.Column("disks_path", sa.String(length=260), nullable=True)
    )

    op.execute(
        """
        UPDATE hyperv_hosts
        SET disks_path = 'C:\\HyperV\\Disks'
        WHERE disks_path IS NULL
        """
    )

    op.alter_column("hyperv_hosts", "disks_path", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hyperv_hosts", "disks_path")
    # ### end Alembic commands ###
