"""Add cluster users

Revision ID: bbed4c82c4d8
Revises: 22acae0a39c5
Create Date: 2025-12-26 21:22:53.713525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.src.database.declarations.cluster_users import (
    CLUSTER_USER_STATUSES_DESCRIPTION,
    ClusterUserStatusEnum,
)


# revision identifiers, used by Alembic.
revision: str = "bbed4c82c4d8"
down_revision: Union[str, Sequence[str], None] = "22acae0a39c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cluster_user_statuses = op.create_table(
        "cluster_user_statuses",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор статуса",
        ),
        sa.Column("status", sa.String(), nullable=False, comment="Имя статуса"),
        sa.Column(
            "description", sa.String(), nullable=True, comment="Описание статуса"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )

    data = []
    for status in ClusterUserStatusEnum:
        data.append(
            {
                "id": status.value,
                "status": status.name,
                "description": CLUSTER_USER_STATUSES_DESCRIPTION[status.value],
            }
        )
    op.bulk_insert(cluster_user_statuses, data)

    op.create_table(
        "cluster_users",
        sa.Column(
            "id",
            sa.String(length=36),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор пользователя",
        ),
        sa.Column(
            "status_id", sa.Integer(), nullable=False, comment="Статус пользователя"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "username", sa.String(length=64), nullable=False, comment="Имя пользователя"
        ),
        sa.Column(
            "permissions",
            sa.String(length=64),
            nullable=False,
            comment="Список привилегий пользователя через запятую",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["cluster_user_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cluster_users_audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
            comment="Пользователь совершивший действие",
        ),
        sa.Column(
            "cluster_user_id",
            sa.String(length=36),
            nullable=False,
            comment="Пользователь кластера над которым произошло изменение",
        ),
        sa.Column("log", sa.String(), nullable=False, comment="Лог изменений"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Время создания лога",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_user_id"],
            ["cluster_users.id"],
            onupdate="restrict",
            ondelete="restrict",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="restrict", ondelete="restrict"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cluster_users_audit")
    op.drop_table("cluster_users")
    op.drop_table("cluster_user_statuses")
    # ### end Alembic commands ###
