"""HyperV host audit

Revision ID: c4e9dd5e9af6
Revises: fcbc950b99f6
Create Date: 2025-11-30 20:21:13.542263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e9dd5e9af6'
down_revision: Union[str, Sequence[str], None] = 'fcbc950b99f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hyperv_hosts_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Пользователь совершивший действие'),
    sa.Column('hyperv_host_id', sa.Integer(), nullable=False, comment='HyperV хост над которым было совершенно действие'),
    sa.Column('log', sa.String(), nullable=False, comment='Лог изменений'),
    sa.ForeignKeyConstraint(['hyperv_host_id'], ['hyperv_hosts.id'], onupdate='restrict', ondelete='restrict'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='restrict', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hyperv_hosts_audit')
    # ### end Alembic commands ###
