"""Add backups table

Revision ID: cac269350a75
Revises: 18a95f4df268
Create Date: 2025-12-26 22:42:16.397224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.src.database.declarations.backup import (
    BackupStatusEnum,
    BackupTypeEnum,
    BACKUP_STATUSES_DESCRIPTION,
    BACKUP_TYPES_DESCRIPTION,
)


# revision identifiers, used by Alembic.
revision: str = "cac269350a75"
down_revision: Union[str, Sequence[str], None] = "18a95f4df268"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    backup_statuses = op.create_table(
        "backup_statuses",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор статуса",
        ),
        sa.Column("status", sa.String(length=32), nullable=False, comment="Статус"),
        sa.Column(
            "description",
            sa.String(length=256),
            nullable=True,
            comment="Описание статуса",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )

    data = []
    for status in BackupStatusEnum:
        data.append(
            {
                "id": status.value,
                "status": status.name,
                "description": BACKUP_STATUSES_DESCRIPTION[status.value],
            }
        )
    op.bulk_insert(backup_statuses, data)

    backup_types = op.create_table(
        "backup_types",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор типа бекапа",
        ),
        sa.Column("type", sa.String(length=32), nullable=False, comment="Тип бекапа"),
        sa.Column(
            "description",
            sa.String(length=256),
            nullable=True,
            comment="Описание типа бекапа",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )

    data = []
    for backup_type in BackupTypeEnum:
        data.append(
            {
                "id": backup_type.value,
                "type": backup_type.name,
                "description": BACKUP_TYPES_DESCRIPTION[backup_type.value],
            }
        )
    op.bulk_insert(backup_types, data)
    op.create_table(
        "backups",
        sa.Column(
            "id",
            sa.String(length=36),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор бекапа (UUID)",
        ),
        sa.Column(
            "cluster_id",
            sa.String(length=36),
            nullable=False,
            comment="Идентификатор кластера, для которого создан бекап",
        ),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Название бекапа, которое ему дал пользователь или система",
        ),
        sa.Column(
            "status_id",
            sa.Integer(),
            nullable=False,
            comment="Идентификатор текущего статуса бекапа",
        ),
        sa.Column(
            "type_id", sa.Integer(), nullable=False, comment="Идентификатор типа бекапа"
        ),
        sa.Column(
            "s3_bucket",
            sa.String(length=255),
            nullable=False,
            comment="Имя S3 бакета, где хранится бекап",
        ),
        sa.Column(
            "s3_key",
            sa.String(length=1024),
            nullable=False,
            comment="Путь к файлу бекапа в S3",
        ),
        sa.Column(
            "s3_region",
            sa.String(length=64),
            nullable=True,
            comment="Регион S3, где хранится бекап",
        ),
        sa.Column(
            "size_bytes",
            sa.BigInteger(),
            nullable=True,
            comment="Размер бекапа в байтах",
        ),
        sa.Column(
            "pg_version",
            sa.String(length=64),
            nullable=False,
            comment="Версия PostgreSQL, с которой был создан бекап",
        ),
        sa.Column(
            "compression",
            sa.String(length=32),
            nullable=True,
            comment="Тип сжатия бекапа (gzip, zstd, none)",
        ),
        sa.Column(
            "backup_method",
            sa.String(length=64),
            nullable=True,
            comment="Метод создания бекапа",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Сообщение об ошибке, если бекап не был создан",
        ),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=True,
            comment="Пользователь, который создал бекап (null для автоматических)",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время начала создания бекапа",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время завершения создания бекапа",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время удаления бекапа",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время истечения срока хранения бекапа",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"], ["clusters.id"], onupdate="restrict", ondelete="restrict"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], onupdate="restrict", ondelete="restrict"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["backup_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["backup_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backups")
    op.drop_table("backup_types")
    op.drop_table("backup_statuses")
    # ### end Alembic commands ###
