"""Clusters, Users, Hosts

Revision ID: fcbc950b99f6
Revises: 
Create Date: 2025-11-30 19:29:33.357647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.src.database.declarations.cluster import CLUSTER_STATUSES_DESCRIPTION, ClusterStatusEnum
from app.src.database.declarations.hyperv_hosts import HypervHostStatusEnum, HYPERV_HOST_STATUSES_DESCRIPTION


# revision identifiers, used by Alembic.
revision: str = 'fcbc950b99f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cluster_statuses = op.create_table('cluster_statuses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='Идентификатор статуса'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Статус'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Описание статуса'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    
    data = []
    for status in ClusterStatusEnum:
        data.append(
            {
                "id": status.value,
                "status": status.name,
                "description": CLUSTER_STATUSES_DESCRIPTION[status.value],
            }
        )
    op.bulk_insert(cluster_statuses, data)
    
    hyperv_hosts_statuses = op.create_table('hyperv_hosts_statuses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='Идентификатор статуса'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Статус'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Описание статуса'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    
    data = []
    for status in HypervHostStatusEnum:
        data.append(
            {
                "id": status.value,
                "status": status.name,
                "description": HYPERV_HOST_STATUSES_DESCRIPTION[status.value],
            }
        )
    op.bulk_insert(hyperv_hosts_statuses, data)
    
    op.create_table('postgres_versions',
    sa.Column('version', sa.String(length=64), nullable=False, comment='Версия постгрес'),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('tg_id', sa.BigInteger(), nullable=True, comment='Идентификатор пользователя в телеграмме'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='Имя пользователя в телеграмме'),
    sa.Column('first_name', sa.String(length=64), nullable=True, comment='Настоящее имя пользователя'),
    sa.Column('last_name', sa.String(length=64), nullable=True, comment='Фамилия пользователя'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли аккаунт пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последней активности'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Включены ли уведомления'),
    sa.Column('permission_level', sa.Integer(), nullable=False, comment='Уровень доступа'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hyperv_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор хоста'),
    sa.Column('host_fqdn', sa.String(length=256), nullable=False, comment='Адрес хоста'),
    sa.Column('winrm_port', sa.Integer(), nullable=False, comment='Порт WinRM'),
    sa.Column('https', sa.Boolean(), nullable=False, comment='Используется ли HTTPS для подключения'),
    sa.Column('location', sa.String(length=128), nullable=True, comment='Локация сервера'),
    sa.Column('description', sa.String(), nullable=True, comment='Дополнительное описание сервера'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Хост Hyper-V, на котором размещён кластер'),
    sa.Column('total_storage', sa.Integer(), nullable=False, comment='Общий объем хранилища в ГБ'),
    sa.Column('total_ram', sa.Integer(), nullable=False, comment='Общий объем оперативной памяти в МБ'),
    sa.Column('total_cpu', sa.Integer(), nullable=False, comment='Общее кол-во ядер процессора'),
    sa.Column('free_storage', sa.Integer(), nullable=False, comment='Свободный объем хранилища в ГБ'),
    sa.Column('free_ram', sa.Integer(), nullable=False, comment='Свободный объем оперативной памяти в МБ'),
    sa.Column('free_cpu', sa.Integer(), nullable=False, comment='Свободное кол-во ядер процессора'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['hyperv_hosts_statuses.id'], onupdate='restrict', ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False, comment='Идентификатор кластера'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Название кластера, которое ему дал пользователь'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='Пользователь, который создал этот кластер'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Идентификатор текущего статуса кластера'),
    sa.Column('pg_version', sa.String(length=64), nullable=False, comment='Версия PostgreSQL'),
    sa.Column('cpu', sa.Integer(), nullable=False, comment='Количество vCPU на хосте кластера'),
    sa.Column('ram_mb', sa.Integer(), nullable=False, comment='Объём ОЗУ в МБ'),
    sa.Column('storage_gb', sa.Integer(), nullable=False, comment='Объём диска для хранилища в ГБ'),
    sa.Column('hyperv_host_id', sa.Integer(), nullable=True, comment='Хост Hyper-V, на котором размещён кластер'),
    sa.Column('postgres_port', sa.Integer(), nullable=True, comment='Порт хоста на который прокинут PostgreSQL порт из вм'),
    sa.Column('ssh_port', sa.Integer(), nullable=True, comment='Порт хоста на который прокинут ssh порт из вм'),
    sa.Column('host_fqdn', sa.String(), nullable=True, comment='Адрес ВМ внутри NAT сети'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hyperv_host_id'], ['hyperv_hosts.id'], onupdate='restrict', ondelete='restrict'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='restrict', ondelete='restrict'),
    sa.ForeignKeyConstraint(['pg_version'], ['postgres_versions.version'], onupdate='restrict', ondelete='restrict'),
    sa.ForeignKeyConstraint(['status_id'], ['cluster_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusters')
    op.drop_table('hyperv_hosts')
    op.drop_table('users')
    op.drop_table('postgres_versions')
    op.drop_table('hyperv_hosts_statuses')
    op.drop_table('cluster_statuses')
    # ### end Alembic commands ###
