- hosts: all
  gather_facts: yes
  become: yes
  become_user: postgres

  roles:
  - role: change_postgresql_conf
    vars:
      postgresql_version: "{{ postgresql_version }}"
      config_params: {}