- hosts: all
  gather_facts: yes
  become: yes

  roles:
  - role: install_postgresql
    vars:
      postgresql_version: "{{ postgresql_version }}"
      db_name: "{{ db_name }}"
      db_user: "{{ db_user }}"
      db_pass: "{{ db_pass }}"
