"""Add users table

Revision ID: 0733acd9bbbf
Revises: 
Create Date: 2025-11-03 13:43:30.647851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0733acd9bbbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('tg_id', sa.BigInteger(), nullable=True, comment='Идентификатор пользователя в телеграмме'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='Имя пользователя в телеграмме'),
    sa.Column('first_name', sa.String(length=64), nullable=True, comment='Настоящее имя пользователя'),
    sa.Column('last_name', sa.String(length=64), nullable=True, comment='Фамилия пользователя'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли аккаунт пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последней активности'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Включены ли уведомления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
