"""Add clusters table

Revision ID: d28615bf5b25
Revises: 0733acd9bbbf
Create Date: 2025-11-03 15:39:24.020118

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from app.src.database.declarations.cluster import (
    CLUSTER_STATUSES_DESCRIPTION,
    ClusterStatusEnum,
)

# revision identifiers, used by Alembic.
revision: str = "d28615bf5b25"
down_revision: Union[str, Sequence[str], None] = "0733acd9bbbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cluster_statuses = op.create_table(
        "cluster_statuses",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор статуса",
        ),
        sa.Column("status", sa.String(), nullable=False, comment="Статус"),
        sa.Column(
            "description",
            sa.String(length=256),
            nullable=True,
            comment="Описание статуса",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )

    data = []
    for status in ClusterStatusEnum:
        data.append(
            {
                "id": status.value,
                "status": status.name,
                "description": CLUSTER_STATUSES_DESCRIPTION[status.value],
            }
        )
    op.bulk_insert(cluster_statuses, data)

    op.create_table(
        "postgres_versions",
        sa.Column(
            "version", sa.String(length=64), nullable=False, comment="Версия постгрес"
        ),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "clusters",
        sa.Column(
            "id",
            sa.String(length=64),
            autoincrement=False,
            nullable=False,
            comment="Идентификатор кластера",
        ),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Название кластера, которое ему дал пользователь",
        ),
        sa.Column(
            "owner_id",
            sa.BigInteger(),
            nullable=False,
            comment="Пользователь, который создал этот кластер",
        ),
        sa.Column(
            "status_id",
            sa.Integer(),
            nullable=False,
            comment="Идентификатор текущего статуса кластера",
        ),
        sa.Column(
            "pg_version",
            sa.String(length=64),
            nullable=False,
            comment="Версия PostgreSQL",
        ),
        sa.Column(
            "cpu",
            sa.Integer(),
            nullable=False,
            comment="Количество vCPU на хосте кластера",
        ),
        sa.Column("ram_mb", sa.Integer(), nullable=False, comment="Объём ОЗУ в МБ"),
        sa.Column(
            "storage_gb",
            sa.Integer(),
            nullable=False,
            comment="Объём диска для хранилища в ГБ",
        ),
        sa.Column(
            "endpoint", sa.String(), nullable=True, comment="Адрес для подключения"
        ),
        sa.Column(
            "port",
            sa.Integer(),
            nullable=True,
            comment="Порт на котором запущен PostgreSQL",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], onupdate="restrict", ondelete="restrict"
        ),
        sa.ForeignKeyConstraint(
            ["pg_version"],
            ["postgres_versions.version"],
            onupdate="restrict",
            ondelete="restrict",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["cluster_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clusters")
    op.drop_table("postgres_versions")
    op.drop_table("cluster_statuses")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
    # ### end Alembic commands ###
